// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQi1x2DdBOMaITNMnry_2ouiZ9PNeXuHk',
    appId: '1:204887592214:web:09793b41af0efc3a639437',
    messagingSenderId: '204887592214',
    projectId: 'mae-project-d86a2',
    authDomain: 'mae-project-d86a2.firebaseapp.com',
    storageBucket: 'mae-project-d86a2.firebasestorage.app',
    measurementId: 'G-WZW6LDX9XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-lmX2_M3WGlhoUj_QdFREKRGJCmQdYw',
    appId: '1:204887592214:android:c7fba6fc4dc5f493639437',
    messagingSenderId: '204887592214',
    projectId: 'mae-project-d86a2',
    storageBucket: 'mae-project-d86a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TE6axZmadcjCsM7EQcC9VkP934_lOZ0',
    appId: '1:204887592214:ios:72fc4756e8588fb5639437',
    messagingSenderId: '204887592214',
    projectId: 'mae-project-d86a2',
    storageBucket: 'mae-project-d86a2.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_TE6axZmadcjCsM7EQcC9VkP934_lOZ0',
    appId: '1:204887592214:ios:72fc4756e8588fb5639437',
    messagingSenderId: '204887592214',
    projectId: 'mae-project-d86a2',
    storageBucket: 'mae-project-d86a2.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQi1x2DdBOMaITNMnry_2ouiZ9PNeXuHk',
    appId: '1:204887592214:web:0b0a358fb435e548639437',
    messagingSenderId: '204887592214',
    projectId: 'mae-project-d86a2',
    authDomain: 'mae-project-d86a2.firebaseapp.com',
    storageBucket: 'mae-project-d86a2.firebasestorage.app',
    measurementId: 'G-MWVN7V3GJN',
  );
}
